# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [79]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [80]:
zeros = np.zeros(9)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [81]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [82]:
zeros.size

9

In [83]:
zeros.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [84]:
np.info(zeros)

class:  ndarray
shape:  (9,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x55f36e6c9580
byteorder:  little
byteswap:  False
type: float64


#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [85]:
arr = np.zeros(12)
arr[5] = 1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [86]:
arr_20_to_59 = np.arange(20,60,1)
arr_20_to_59

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [87]:
arr_reverse_before = np.arange(1,10,1)
arr_reverse_after = arr_reverse_before[::-1]
arr_reverse_after

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [88]:
arr_12_to_20 = np.arange(12,21,1).reshape((3,3))
arr_12_to_20

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [89]:
arr_index_zeros = np.array([3, 7, 0, 0, 9, 0])
#np.where(arr_index_zeros !=0)
np.nonzero(arr_index_zeros)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [90]:
np.random.randn(8).reshape((2,2,2))

array([[[ 0.31265438,  1.80880461],
        [-1.74301607, -1.23024044]],

       [[ 0.71337865,  0.87462142],
        [-0.90271242, -1.15481429]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [91]:
arr_max_min = np.random.randn(81).reshape((9,9))
arr_max_min

array([[-0.61448487,  0.6006509 , -0.36504411, -0.09154217, -0.43104   ,
        -0.28868254, -0.74624105,  0.97437363, -0.05745449],
       [-1.66575228, -0.09472896,  1.46369608,  2.27648332,  0.9462952 ,
        -1.16775823,  0.3827649 ,  1.2379003 ,  2.15000142],
       [ 0.25403167, -0.99396625,  0.08913643, -0.53226553,  0.24749658,
         2.47346633,  0.01622193,  0.40150477, -0.71588784],
       [-2.17839318,  0.12486404, -0.67471188, -1.65258667,  0.60141808,
        -1.12048835,  1.52133455, -0.08794059, -0.62464074],
       [-1.10927819, -0.41580616,  1.33453711, -0.73893157,  1.01087484,
         0.1685925 , -0.33871971, -0.51511735, -2.32264646],
       [ 1.01970381, -0.78352031,  1.12305193,  0.40251589, -0.35551966,
         0.21063588, -1.08835823, -1.14623556, -0.50933563],
       [-0.02125068, -0.49130239, -0.06597575,  1.05836094,  0.80646521,
         0.24606296,  0.65359471,  0.97954513, -1.23269061],
       [ 0.11354356,  0.89817818,  0.03155085, -2.25815429, -1

In [92]:
max = np.max(arr_max_min)
max

2.4734663270934676

In [93]:
min = np.min(arr_max_min)
min

-2.3226464578648294

In [94]:
max_index = arr_max_min.argmax()
max_index

23

In [95]:
min_index = arr_max_min.argmin()
min_index

44

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [96]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [97]:
arr1_mult = np.ones(18).reshape((6,3))
arr2_mult = np.ones(12).reshape((3,4))
res = np.dot(arr1_mult,arr2_mult)
res

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [98]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [101]:
arr1 = np.array([1,2])
arr2 = np.array([4,5])
res1 = arr1 > arr2
res1

array([False, False])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [102]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-102-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-102-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-102-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [107]:
arr1 = np.arange(1,10,1)
arr2 = np.arange(5,20,2)
arr2


array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [108]:
res = np.intersect1d(arr1, arr2)
res

array([5, 7, 9])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [126]:
arr_ran5 = np.random.randn(5)
arr_ran5

array([ 0.25403671, -0.01730513, -1.49574648,  1.64589808,  0.43330507])

In [128]:
mask = arr_ran5 > 0

In [130]:
our_pos_arr_ran5 = arr_ran5[mask]
our_pos_arr_ran5

array([0.25403671, 1.64589808, 0.43330507])

In [133]:
first_way = our_pos_arr_ran5.astype('int64')
first_way

array([0, 1, 0])

In [135]:
second_way = np.floor(our_pos_arr_ran5)
second_way

array([0., 1., 0.])

In [136]:
third_way = np.trunc(our_pos_arr_ran5)
third_way

array([0., 1., 0.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [145]:
arr_3x3 = np.arange(0,3,1)
big_arr = np.stack((arr_3x3,arr_3x3,arr_3x3), axis = 0)
big_arr

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [148]:
arr = np.random.randn(10)
arr

array([-0.19200383,  0.0987025 , -0.87773489,  0.48394924, -0.35439645,
       -2.8175194 ,  0.48880679,  0.86366172,  0.58089659,  0.55294318])

In [149]:
res = np.sort(arr)
res

array([-2.8175194 , -0.87773489, -0.35439645, -0.19200383,  0.0987025 ,
        0.48394924,  0.48880679,  0.55294318,  0.58089659,  0.86366172])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [150]:
arr1 = np.random.randn(3)
arr2 = np.random.randn(3)

res1 = np.allclose(arr1, arr2)
res1

False

In [151]:
res2 = np.array_equal(arr1, arr2)
res2

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [152]:
arr1_mult = np.ones(18).reshape((6,3))
arr2_mult = np.ones(12).reshape((3,4))
res = np.dot(arr1_mult,arr2_mult)
res

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [153]:
arr = np.random.randn(5)
arr

array([-1.41616188,  1.25621566,  0.10715193,  0.32800984, -0.32979553])

In [157]:
arr[np.argmax(arr)] = 0
arr


array([-1.41616188,  0.        ,  0.10715193,  0.32800984, -0.32979553])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [169]:
import datetime as dt
now = dt.datetime.now()
now_np = np.datetime64(now)
now_np

numpy.datetime64('2024-07-01T04:18:40.821586')

In [171]:
yesterday = now - dt.timedelta(days = 1)
yesterday

datetime.datetime(2024, 6, 30, 4, 18, 40, 821586)

In [172]:
tomorrow = now + dt.timedelta(days = 1)
tomorrow

datetime.datetime(2024, 7, 2, 4, 18, 40, 821586)

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [205]:
import numpy as np

# Get the current date
current_date = np.datetime64('today', 'D')

# Generate an array of dates from 30 days ago to today
# np.arange() will generate dates from start to end (not inclusive of end)
num_days = 30
num_years = 365
date_array = np.arange(current_date - (np.timedelta64(num_years, 'D')*8 + np.timedelta64(num_days, 'D')*6 + 4),
                       current_date - (np.timedelta64(num_years, 'D')*8 + np.timedelta64(num_days, 'D')*5+4),
                       dtype='datetime64[D]')

print("Array of previous dates:", date_array)

Array of previous dates: ['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [98]:
#Done

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [212]:
arr1 = np.arange(0,5,1)
arr2 = np.arange(5,10,1)

%time np.sum(arr1)

CPU times: user 75 µs, sys: 0 ns, total: 75 µs
Wall time: 79.6 µs


10

In [213]:
%time np.add.reduce(arr1)

CPU times: user 48 µs, sys: 4 µs, total: 52 µs
Wall time: 56 µs


10

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [219]:
arr_org = np.arange(1,6,1)
arr_org

array([1, 2, 3, 4, 5])

In [225]:
num_zeros = 3

zeros = np.zeros(len(arr_org)*(num_zeros+1)-num_zeros,dtype=int)
zeros[::num_zeros+1] = arr_org
zeros

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [248]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
b = np.array([])
for i in range(len(a)-2) :
  temp = np.arange(i,i+4,1)





#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [247]:
arr = np.array([1,2,3,5,6,8,9,1,44,3,5,9,44])
arr_sorted = np.sort(arr)
arr_sorted

res = []

for i in range(len(arr_sorted)-1):
  if arr_sorted[i] == arr_sorted[i+1]:
    res.append(arr_sorted[i+1])
res




[1, 3, 5, 9, 44]

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`