In [5]:
import numpy as np


In [6]:
my_list = list(range(100000)) #normal
my_array = np.array(range(100000))

In [7]:
%time for _ in range(10):[x*2 for x in my_list] #normal

CPU times: user 84.8 ms, sys: 7.9 ms, total: 92.7 ms
Wall time: 101 ms


In [8]:
%time for _ in range(10):my_array*2 #vektorlashgan

CPU times: user 2.3 ms, sys: 0 ns, total: 2.3 ms
Wall time: 4.89 ms


In [9]:
74.9/2.28

32.85087719298246

In [10]:
data1 = [[1,2,3,4,5],[6,7,8,9,10],[77,88,99,11,66]]
arr1 = np.array(data1)  # convert list to array
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [77 88 99 11 66]]


In [11]:
arr1.ndim #dimension

2

In [12]:
arr1.shape

(3, 5)

In [13]:
arr1.size

15

In [14]:
arr2 = np.ones((3,31))
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
arr3 = np.zeros((3,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr4 = np.eye(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr4 = np.diag([1,2,3])
arr4

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [18]:
arr5 = np.arange(10,23,3)
arr5

array([10, 13, 16, 19, 22])

In [19]:
arr6 = np.arange(0,np.random.randint(100,1000),np.random.randint(3,10))


print(arr6)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900]


In [20]:
def two_dim(r,c):
  arr7 = np.random.randint(100,1000,(r,c))
  return arr7

In [21]:
two_dim(8,9)

array([[409, 813, 352, 288, 491, 507, 207, 179, 979],
       [649, 653, 403, 594, 921, 431, 744, 885, 471],
       [428, 971, 420, 636, 668, 636, 513, 749, 303],
       [190, 381, 570, 924, 186, 633, 684, 646, 537],
       [194, 337, 544, 983, 492, 251, 699, 712, 548],
       [889, 261, 755, 627, 863, 471, 449, 164, 698],
       [458, 148, 496, 374, 922, 792, 289, 497, 229],
       [446, 199, 346, 836, 794, 742, 822, 352, 120]])

In [22]:
arr8 = np.array([1,4,6])
print(arr8)
print(arr8.dtype)

[1 4 6]
int64


In [23]:
arr9 = np.array([1,4,6],dtype=np.float64)
print(arr9)
print(arr9.dtype)

[1. 4. 6.]
float64


In [24]:
arr10 = np.arange(5,50,2)
print(arr10[10])
arr10

25


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [25]:
print(arr10[2:5])

[ 9 11 13]


In [26]:
sliced_arr = arr10[5:7].copy()
sliced_arr[:] = 0
print(arr10)
print(sliced_arr)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
[0 0]


In [27]:
names = np.array(["ali", "vali","hasan", "qodir", "hasan"])
print(names)

['ali' 'vali' 'hasan' 'qodir' 'hasan']


In [28]:
data = np.random.randn(5,4)
data

array([[ 0.75194672, -1.49441955,  0.02704693,  1.4537866 ],
       [ 1.28578504,  0.80399061, -0.05551702,  0.58755202],
       [ 0.92446946, -0.20842666,  1.21117979,  1.54716984],
       [-1.76319556,  0.17821339,  0.12635976, -1.52316544],
       [ 1.41667999, -0.10320041,  0.51732168,  0.04806457]])

In [29]:
print(data[~(names == "hasan")])

[[ 0.75194672 -1.49441955  0.02704693  1.4537866 ]
 [ 1.28578504  0.80399061 -0.05551702  0.58755202]
 [-1.76319556  0.17821339  0.12635976 -1.52316544]]


In [30]:
res1 = data[names == "hasan"]
res2 = data[names == "vali"]
res = np.vstack([res1,res2]) # Use vstack to vertically stack arrays of different number of rows

res

array([[ 0.92446946, -0.20842666,  1.21117979,  1.54716984],
       [ 1.41667999, -0.10320041,  0.51732168,  0.04806457],
       [ 1.28578504,  0.80399061, -0.05551702,  0.58755202]])

In [31]:
data= np.arange(0,9,1).reshape(3,3)
data


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
sliced_array_2 = data[2,0:2]
sliced_array_2

array([6, 7])

In [33]:
data_3d = np.arange(0,27,1).reshape(3,3,3)
data_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
sliced_array_3 = data_3d[1,1,0:]
sliced_array_3

array([12, 13, 14])

In [35]:
sliced_array_3 = data_3d[2,0,1:]
sliced_array_3

array([19, 20])

Transposing&&Swapping

In [36]:
A = np.arange(0,12,1).reshape(3,4)
A


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
print(A.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [38]:
A.swapaxes(0,1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [39]:
print(np.dot(A,A.T))

[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


**Where** shart operatori

In [40]:
arr11 = np.random.randn(5,6)
arr11

array([[ 0.33689032,  2.52554206,  0.26593853,  0.17104301,  1.17628625,
        -0.08318843],
       [ 1.69399596,  0.84595175, -0.09475184,  0.9010236 ,  1.9209507 ,
        -0.42432009],
       [-0.20989849, -0.19644681,  0.56147165,  0.30160201,  0.80515239,
         1.35462582],
       [-0.9947074 , -1.07168397,  1.34836824, -0.53000492, -0.15603652,
         0.61621805],
       [-1.33040522,  0.11686638,  1.07820789, -0.40871483,  0.75884263,
         0.52681031]])

In [41]:
results = np.where(arr11>0,0,-1)
results

array([[ 0,  0,  0,  0,  0, -1],
       [ 0,  0, -1,  0,  0, -1],
       [-1, -1,  0,  0,  0,  0],
       [-1, -1,  0, -1, -1,  0],
       [-1,  0,  0, -1,  0,  0]])

In [42]:
%time results = np.where(arr11 > 0, 0, -1)

CPU times: user 37 µs, sys: 4 µs, total: 41 µs
Wall time: 44.6 µs


**Unique, in1d, setdiff1d** methodlari

In [43]:
names = np.array(["ali", "vali","hasan", "qodir", "hasan","hasan", "ali"])
unique_names = np.unique(names)
unique_names

array(['ali', 'hasan', 'qodir', 'vali'], dtype='<U5')

In [44]:
arr_big = np.arange(5,15,2)
arr_sm = [5,6,7]
arr_big

array([ 5,  7,  9, 11, 13])

In [45]:
in_arr = np.in1d(arr_big,arr_sm)
in_arr

array([ True,  True, False, False, False])

In [46]:
names1= np.array(["ali", "vali","hasan", "qodir", "hasan","hasan", "ali"])
names2 = np.array(["ali", "muhammad","zokir"])
set_diff = np.setdiff1d(names1,names2)
set_diff

array(['hasan', 'qodir', 'vali'], dtype='<U5')

File

In [47]:
arr1= np.arange(10)
arr2 = np.arange(10,20,1)

In [48]:
saved_arr1 = np.save('data1.npy', arr1)
saved_arr2 = np.save('data2', arr2)

In [49]:
saved_arr3 = np.savez('data3.npz', a = arr1, b = arr2)

In [50]:
arrays = np.load('data3.npz')
arrays['b']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

**TASK GM**

In [51]:
!wget -O GM_Cars.zip "https://drive.google.com/uc?export=download&id=1i57swZxVA9Xh64eVvylnkIJmKT-4WTZy" && unzip GM_Cars.zip && rm -r GM_Cars.zip

--2024-06-30 23:38:11--  https://drive.google.com/uc?export=download&id=1i57swZxVA9Xh64eVvylnkIJmKT-4WTZy
Resolving drive.google.com (drive.google.com)... 64.233.187.113, 64.233.187.138, 64.233.187.101, ...
Connecting to drive.google.com (drive.google.com)|64.233.187.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1i57swZxVA9Xh64eVvylnkIJmKT-4WTZy&export=download [following]
--2024-06-30 23:38:12--  https://drive.usercontent.google.com/download?id=1i57swZxVA9Xh64eVvylnkIJmKT-4WTZy&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.8.132, 2404:6800:4008:c15::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.8.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 793 [application/octet-stream]
Saving to: ‘GM_Cars.zip’

GM_Cars.zip         100%[===================>]     793  --.-KB/s    in 0s      


In [65]:
gm_cars_2020 = np.load('/content/GM_Cars/gm_2020.npz')
gm_cars_2021 = np.load('/content/GM_Cars/gm_2021.npz')
gm_cars_2020['models']


array(['Labo', 'Damas', 'Spark', 'Nexia', 'Cobalt', 'Gentra'], dtype='<U6')

In [64]:
gm_cars_2020['qnts']

array([ 4521, 30889, 16370, 41663, 44901, 30368], dtype=int32)

In [73]:
gm_cars_2021['qnts']

array([ 7542, 33682,  6485, 14442, 36317, 26266], dtype=int32)

**Total quantities**

In [67]:
sum1 = np.sum(gm_cars_2020['qnts'])
sum2 = np.sum(gm_cars_2021['qnts'])
sum = sum1 + sum2
sum

293446

Faqat Damas, Nexia, Cobalt va Gentra ma'lumotlarini ajratib olish

In [72]:
all_qnts = gm_cars_2020['qnts'] + gm_cars_2021['qnts']
all_qnts

array([12063, 64571, 22855, 56105, 81218, 56634], dtype=int32)

In [75]:
sum_all_these_cars_qnts= np.add(np.sum(gm_cars_2020['qnts']),np.sum(gm_cars_2021['qnts']))
sum_all_these_four_cars_qnts= sum_all_these_cars_qnts- all_qnts[0]-all_qnts[2]
sum_all_these_four_cars_qnts

258528

Percenntage of damas in the 2 years average


In [81]:
percentage_of_damas = np.sum(gm_cars_2020['qnts'][1]+gm_cars_2021['qnts'][1])/sum_all_these_cars_qnts * 100
percentage_of_damas

22.00438922323017

Percentage of damas in 2020

In [84]:
percentage_of_damas_2020 = (gm_cars_2020['qnts'][1]/np.sum(gm_cars_2020['qnts'])) * 100
percentage_of_damas_2020

18.30871544407037

Percenntage of damas in 2021

In [85]:
percentage_of_damas_2021 = (gm_cars_2021['qnts'][1]/np.sum(gm_cars_2021['qnts'])) * 100
percentage_of_damas_2021

27.003062517036252

Percentage of gentra in the two years

In [83]:
percentage_of_gentra = np.sum(gm_cars_2020['qnts'][5]+gm_cars_2021['qnts'][5])/sum_all_these_cars_qnts * 100
percentage_of_gentra

19.299632641099215

In [86]:
a = np.array([[1,2],[2,3]])
a.itemsize

8

**YAKUNIY VAZIFA** NumPy...

In [ ]:
#on_process